name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: Clean install
      run: npm ci
    - name: Build
      run: npm build --if-present
    - name: Lint code
      run: npm run lint
